### ISSUE TITLE
Pull Requests?

### ISSUE THREAD

**Issue by joefiorini** [livingsocial/rake-pipeline#124]
I have 4 pull requests (#113, #112, #111, #88) currently open and I'm about to send another. I understand if no one has had time to review them, but if I'm dong something wrong (or just not useful) can someone please let me know? I'd like to improve for these and future pull requests. Thanks!

**Comment by wagenet** [comment]
Rake Pipeline is still an active project but our priorities have largely been elsewhere. Hopefully we can get some review on your patches soon.

**Comment by ronaldocpontes** [comment]
Have the pull requests being reviewed?

I am specially interested in the solution for this problem:
https://github.com/livingsocial/rake-pipeline/issues/98

Thanks
