### ISSUE TITLE
Support multiple outputs for the same input

### ISSUE THREAD

**Issue by jamesarosen** [livingsocial/rake-pipeline#22]
A CacheBustingFilter would ideally behave as follows:
- take input from `input/foo.css`
- write it directly to `output/foo.css`
- also write to `output/foo-abcde123456.css`

I would imagine the following syntax:

``` ruby
filter MyFilter do |input|
  [ input, hashify(input) ]
end
```

(where `hashify` is something `MyFilter` defines).

**Comment by jamesarosen** [comment]
I can work on this later if no one else picks it up. I just wanted there to be a placeholder.

**Comment by jamesarosen** [comment]
I _believe_ this will also satisfy the following use case:

Inputs:
- common.js
- stuff_for_desktop.js
- stuff_for_mobile.js

Outputs:
- desktop.js ( common.js + stuff_for_desktop.js )
- mobile.js ( common.js + stuff_for_mobile.js )

With the following Assetfile:

``` ruby
filter ConcatFilter do |input|
  return [ 'desktop.js', 'mobile.js' ] if input =~ /common/
  return input.sub('stuff_for_', '')
end
```

**Comment by wycats** [comment]
Done and done. Worth noting that you probably mean continue and not return in your block... And I'd probably do:

``` ruby
filter ConcatFilter do |input|
  if input =~ /common/
    [ 'desktop.js', 'mobile.js' ]
  else
    input.sub('stuff_for_', '')
  end
end
```

**Comment by jamesarosen** [comment]
That's exactly what I mean :)
