### ISSUE TITLE
Should we copy all files by default?

### ISSUE THREAD

**Issue by dudleyf** [livingsocial/rake-pipeline#30]
19309919b2bb151238022a0cb82d82d0b9e47df7 added a concat filter to the end of every pipeline so that all unmatched inputs get copied to the output directory. Is this actually a good idea? Now everything gets copied whether we want it to or not. I think we either need to be able to exclude files somehow, or we revert back to making people add their own concat filter to the end if they want it. I'm leaning toward the latter, since it's much easier to implement :)

**Comment by bruce** [comment]
+1 to reverting this change, or at least offering a way to exclude them.  (In the very least this will help cut down on `#emacsswapfiles#` and such transient fluff being copied over unintentionally. )
