### ISSUE TITLE
matches generate tmp directories

### ISSUE THREAD

**Issue by tkellen** [livingsocial/rake-pipeline#55]
Because matches are also filters, they generate extraneous temp directories.

For a reproduction, clone this repo:
https://github.com/tkellen/rake-pipeline-ember-skeleton

...run bundle install / bundle rakep build and inspect the resulting tmp dir.

**Comment by dudleyf** [comment]
It's actually because Matchers are also Pipelines. They were getting an unnecessary PipelineFinalizingFilter added to their filter chain. I've got a [fix](https://github.com/dudleyf/rake-pipeline/commit/7846d20e2d0ad5557c765b2ff3c56a9a42ed627a) that should get pulled in soon.
