### ISSUE TITLE
Declaring dependencies of inputs

### ISSUE THREAD

**Issue by ppcano** [livingsocial/rake-pipeline#62]
I think the maintainers are yet notified about this feature. With the current implementation, if i use import statements which points to other files, and updates the import/dependent file, this won't be added to the next output file.

Below, i wanted to share an api suggestions.

``` ruby

input "less" do

  match "views/*.less" depends "import/*.less" do
     filter CustomFilter
     concat "project.css"
  end

end

```

**Comment by ahawkins** [comment]
@ppcano this is fixed in 0.7.0 (just released a few days ago). @wycats you can close this one.

**Comment by manoharank** [comment]
@twinturbo @ppcano What would be the solution for this problem? I can't figure out.

**Comment by ahawkins** [comment]
@manoit88 see the `DynamicFileTask`. All filters have an `additional_inputs` method for this use case. IE they can return all the files imported (LESS/SASS).

**Comment by manoharank** [comment]
@twinturbo Thank you.
