### ISSUE TITLE
Output of multiple match filters concats to the same output file

### ISSUE THREAD

**Issue by ppcano** [livingsocial/rake-pipeline#68]
I would like all my javascript being concatanated to one file

``` html

<script type="text/javascript" src="source/app.js"></script>

```

My current AssetFile which does not work would be something like:

``` ruby
input "assets/vendor" do
  match "*.js" do
           filter Rake::Pipeline::OrderingConcatFilter,
            ["minispade.js", "qrcode.js", "jquery.js", "jquery.transit.js"], "app.js"
  end

end




input "packages" do

match "*/lib/**/*.js" do
  minispade :rewrite_requires => true, :string=> false, :module_id_generator => proc { |input|
    id = input.path.dup
    id.sub!('/lib/', '/')
    id.sub!(/\.js$/, '')
    id.sub!(/\/main$/, '')
    id
  }

    filter ConcatFilter, "app.js"
  end

end

input "app" do

  match "*/lib/**/*.js" do
    minispade :rewrite_requires => true, :string=> false, :module_id_generator => proc { |input|
    id = input.path.dup
    id.sub!('/lib/', '/')
    id.sub!(/\.js$/, '')
    id.sub!(/\/main$/, '')
    id
  }
   filter ConcatFilter, "app.js"
   end

end

```

Any workaround to make that possible?

**Comment by dudleyf** [comment]
If you want to concat to the same file, your `match` blocks need to be inside the same `input` block. Each `input` block defines a separate pipeline, and each pipeline creates its output files from scratch, so your pipelines will overwrite each other.

**Comment by ppcano** [comment]
Thanks, i got it working on the following [gist](https://gist.github.com/2030110).

Just wanting to point that the filter _Rake::Pipeline::OrderingConcatFilter_ was not working that why i need to create multiple matchs for each independent file. Instead of something like:

``` ruby
match "*.js" do
    filter Rake::Pipeline::OrderingConcatFilter, ["minispade.js", "qrcode.js","jquery.js", "jquery.transit.js"], "vendor.js"
end
```

I guess, the current behavior is that the output concat order is being on the opposite order of the match definitions, so my last match definition will be written at the top of the output file.

Feel free to close the ticket, thanks.

**Comment by dudleyf** [comment]
In the gist you posted, you're matching `vendor/minispade.js`, etc. You need to provide that same path (with the `vendor/` prefix) to the concat filter. If the input filenames don't match exactly, the OrderingConcatFilter won't tell you anything's wrong, it'll just concat in whatever order it wants to.
Also, you can just use `concat` instead of `filter Rake::Pipeline::OrderingConcatFilter`. When you pass an array to concat, it uses the ordering concat filter.
