### ISSUE TITLE
Make provisions for filters that can output two files

### ISSUE THREAD

**Issue by rstacruz** [livingsocial/rake-pipeline#82]
I'm trying to concatenate all my scripts into `app.raw.js` (uncompressed) and and `app.min.js` (compressed) using `rake-pipeline-web-filters`. Here's my solution:

``` ruby

['raw', 'min'].each do |type|
  input "src" do
    match "*.coffee" do
      coffee_script
      concat %w[
        start.js
        base.js
        line.js
      ], "app.#{type}.js"

      uglify  if type == 'min'
    end
  end
end
```

...However, it feels hackish because this will needlessly invoke `coffee_script` twice per file. I was expecting a solution more along the lines of:

``` ruby
input "src" do
  match "*.coffee" do
    coffee_script
    concat %w[
      start.js
      base.js
      line.js
    ], "app.js"
  end

  match "app.js" do
    copy "app.raw.js"
    copy "app.min.js" # <-- doesn't work: this effectively renames app.raw.js to app.min.js, not copying it.
  end

  match "app.min.js" do
    uglify
  end
end
```

**Comment by wycats** [comment]
Filters can currently output multiple files (if their block returns an Array instead of an individual file). Does this solve your problem?

**Comment by wagenet** [comment]
@wycats I imagine this is safe to close.

**Comment by ahawkins** [comment]
no doubt.

``` ruby
match "**/*.js" do
   concat ["application.js", "application.min.js"]
end

match "application.min.js" do
  # minify it
end
```

This is also covered in the examples directory.

@wycats This is safe to close
