### ISSUE TITLE
Server Middleware blows up if pass Project instead of  Pipeline

### ISSUE THREAD

**Issue by ahawkins** [livingsocial/rake-pipeline#84]
I came across this in iridium. I had created a Project from an assetfile and stupidly passed this to the middleware when it expects a Pipeline or Assetfile. A Project is instantiated from the pipeline argument which creates nested projects. Project don't have `output_root` so you get weird errors.

**Comment by wycats** [comment]
What behavior do you want here? Would an error message be enough?

**Comment by ahawkins** [comment]
I no longer feel this is important.
