### ISSUE TITLE
How to use rake-pipeline for assets development?

### ISSUE THREAD

**Issue by mulderp** [livingsocial/rake-pipeline#89]
I've recently discovered the rake pipeline by looking at the Travis-CI setup, and it looks interesting to me, to separate assets for client-side and server-side code into separate Rails engines.
However, as I am new to the rake pipeline project, it's a bit unclear to me how to use this setup in development mode, where I prefer working with modular files.
1.  Using the Rake::Pipeline::ConcatFilter generates one big, "compiled" file, if I understand correctly, but in development mode, I just want to compile .less, .coffee to corresponding .css and .js without concatenation. How would I do this?
2. If I use modular CSS frameworks, like bootstrap, I would accept the concatenation of files, however, there are custom variables, which I want to set separately in a custom less files. Is there a way to selectively concatenate files?

I could share some code of the experiments that I did, if it would be helpful. 

Thanks for feedback!

**Comment by ahawkins** [comment]
You cannot do 1. That is completely against what rake pipeline does. You can use an ordered concat filter for #2.

**Comment by mulderp** [comment]
Thanks for the feedback!
For 1 ->  I only have a basic understanding of how Asset packaging should be done, so no more discussion needed here, but I saw another small comment which requires a copy use case instead of concatenation: https://github.com/travis-ci/travis-assets/blob/master/AssetFile#L92

For 2 -> Thanks for giving a pointer

**Comment by wagenet** [comment]
@mulderp Should this be closed?

**Comment by mulderp** [comment]
yes!
Couldn't really continue much on my setup. Hopefully in the next weeks more exploration.

**Comment by manoharank** [comment]
@twinturbo @mulderp 

For 1 i have done in the following way

``` ruby
output "css"
input "less/*.less" do
  LessFilter
end

# Only for production
if PROD
  input "css/*.css" do
    concat "app.css"
  end
end
```
